remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-redirect-from
title: F-Shop Documentation
description: Документация WordPress плагина F-Shop
show_downloads: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed 