remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-redirect-from
title: F-Shop Documentation
description: Документация WordPress плагина F-Shop
show_downloads: false
baseurl: "/f-shop"
url: "https://karakushan.github.io"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
sass:
  style: compressed 