remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: F-Shop Documentation
description: Документация WordPress плагина F-Shop
show_downloads: false
baseurl: "/f-shop"
search_enabled: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge 